import React from "react";
import {status} from "../../constants/orderStatus";

export default class OrderByAccessory extends React.Component{
    render(){
        return(
            <React.Fragment>
                <tr>
                    <td>
                        {
                            this.props.order_item.order[0].user_name
                        }
                    </td>
                    <td>
                        {
                            this.props.order_item.price
                        }
                    </td>
                    <td>
                        {
                            this.props.order_item.quantity
                        }
                    </td>
                    <td>
                        {
                            this.props.order_item.total_price
                        }
                    </td>
                    <td>
                        {
                            this.props.order_item.order[0].order_date
                        }
                    </td>
                    <td>
                        {
                            this.props.order_item.order[0].tax
                        }
                    </td>
                    <td>
                        {
                            this.props.order_item.order[0].delivery_fee
                        }
                    </td>
                    <td>
                        {
                            status(this.props.order_item.order[0].status_id)
                        }
                    </td>
                </tr>
            </React.Fragment>
        )
    }
}