import React from 'react';
import {status} from "../../constants/orderStatus";

export default class OrderItem extends React.Component{
    render(){
        return(
            <React.Fragment>
                <tr>
                    <td>
                        {
                            this.props.orders.user_name
                        }
                    </td>
                    <td>
                        {
                            this.props.orderItem.accessory_name
                        }
                    </td>
                    <td>
                        {
                            this.props.orderItem.price
                        }
                    </td>
                    <td>
                        {
                            this.props.orderItem.quantity
                        }
                    </td>
                    <td>
                        {
                            this.props.orderItem.total_price
                        }
                    </td>
                    <td>
                        {
                            this.props.orders.order_date
                        }
                    </td>
                    <td>
                        {
                            status(this.props.orders.status_id)
                        }
                    </td>
                    <td>
                        {
                            this.props.orders.tax
                        }
                    </td>
                    <td>
                        {
                            this.props.orders.delivery_fee
                        }
                    </td>
                </tr>
            </React.Fragment>
        );
    }
}